// Builds FrameworkTestPreset.ini via the framework's own M8rJSON Stringify,
// then round-trips Parse to prove the file is loadable.
#include "MCM/M8rIniJson.h"

#include <cstdio>
#include <fstream>
#include <string>

using namespace M8rIniJson;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: make_test_preset <out.ini>\n");
        return 2;
    }

    Value root = Value::MakeObject();

    // CapsWidget — property ints (Nuka style + tall height = easy visual markers)
    root.Set({"CapsWidget", "prp", "CapsWidget.esp", "F99", "iStyle"}, Value::MakeInt(2));
    root.Set({"CapsWidget", "prp", "CapsWidget.esp", "F99", "iHeight"}, Value::MakeInt(500));

    // FastAddItemMenu — F10
    root.Set({"FastAddItemMenu", "hot", "OpenAddItemMenuKey"}, Value::MakeString("121;0"));

    // UneducatedShooter — lean hotkeys + distinctive inertia markers
    root.Set({"UneducatedShooter", "hot", "keyLeanLeft"}, Value::MakeString("69;0"));
    root.Set({"UneducatedShooter", "hot", "keyLeanRight"}, Value::MakeString("81;0"));
    root.Set({"UneducatedShooter", "ini", "Inertia", "frotLimitX"}, Value::MakeDouble(12.3));
    root.Set({"UneducatedShooter", "ini", "Inertia", "frotLimitY"}, Value::MakeDouble(0.0));
    root.Set({"UneducatedShooter", "ini", "Inertia", "frotDivX"}, Value::MakeDouble(50.0));
    root.Set({"UneducatedShooter", "ini", "Inertia", "frotDivY"}, Value::MakeDouble(50.0));
    root.Set({"UneducatedShooter", "ini", "Inertia", "brotDisableInADS"}, Value::MakeInt(0));
    root.Set({"UneducatedShooter", "ini", "Leaning", "bleanDisable"}, Value::MakeInt(0));
    root.Set({"UneducatedShooter", "ini", "Realism", "bRealism"}, Value::MakeInt(0));

    // UnlimitedSurvivalMode — bools stored as 1/0 like real MCM exports
    root.Set({"UnlimitedSurvivalMode", "ini", "Settings", "iEnableFastTravel"}, Value::MakeInt(1));
    root.Set({"UnlimitedSurvivalMode", "ini", "Settings", "iEnableConsole"}, Value::MakeInt(1));
    root.Set({"UnlimitedSurvivalMode", "ini", "Settings", "iEnableQuickSave"}, Value::MakeInt(1));

    // WorkshopFramework — P
    root.Set({"WorkshopFramework", "hot", "StartupWorkshop"}, Value::MakeString("80;0"));

    const std::string wire = Stringify(root);
    auto back = Parse(wire);
    if (!back || Stringify(*back) != wire) {
        std::printf("FAIL round-trip\n");
        std::printf("wire: %s\n", wire.c_str());
        return 1;
    }

    std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
    if (!out) {
        std::printf("FAIL write %s\n", argv[1]);
        return 1;
    }
    out << "; F4SE Menu Framework: MCM Settings Manager smoke-test preset for TMR.\n"
           "; Generated by swf/test/make_test_preset.cpp (M8rJSON via framework codec).\n"
           "; Display name = file stem. New presets need a game restart under MO2.\n"
           ";\n"
           "; Markers to verify after Apply:\n"
           ";   UneducatedShooter Inertia Rotation Limit X = 12.3\n"
           ";   UneducatedShooter Disable Inertia In ADS   = OFF\n"
           ";   Caps Widget Cap Style                      = Nuka Cola\n"
           ";   Caps Widget Vertical Position              = 500\n"
           ";   Unlimited Survival Mode Fast Travel/Console/Quick Save = ON\n"
           ";   Hotkeys: Lean L/R = E/Q, Fast Add Item = F10, Workshop = P\n"
           "\n"
           "[MCMSettings]\n"
           "sSettings="
        << wire << "\n";
    out.close();

    // Re-read the way the framework page does (scan for sSettings=).
    std::ifstream in(argv[1], std::ios::binary);
    std::string content((std::istreambuf_iterator<char>(in)),
                        std::istreambuf_iterator<char>());
    auto pos = content.find("sSettings=");
    auto payload = content.substr(pos + 10);
    while (!payload.empty() && (payload.back() == '\n' || payload.back() == '\r'))
        payload.pop_back();
    auto fileParsed = Parse(payload);
    if (!fileParsed || Stringify(*fileParsed) != wire) {
        std::printf("FAIL file re-parse\n");
        return 1;
    }

    std::printf("OK wrote %s (%zu bytes, %zu mods)\n", argv[1], wire.size(),
                root.object.size());
    std::printf("%s\n", wire.c_str());
    return 0;
}
